title: PowerSense
description: A research lab focused on producing tools at the cross-section of power system operations, applied mathematics, high-performance computations, and machine-learning 
show_downloads: true
google_analytics: G-T40CJX2T9Y
theme: jekyll-theme-cayman
