title: ACOPF Formulations
description: This project provides a Julia based platform to use nine different ACOPF formualtions for a transmission systems.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
